name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Init Env
      run: go install github.com/tc-hib/go-winres@latest

    - name: Build
      run: go-winres make && go build -ldflags="-H windowsgui"
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
