name: Go

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Init Env
      run: go install github.com/tc-hib/go-winres@latest

    - name: Build for Windows
      run: |
        go-winres make
        go build -ldflags="-H windowsgui -s -w"
        dir

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: BurpSuitePro.exe
